orbite: "ASC"

request: "(date.dt.month == 3 and date.dt.day== 1) and ((elevation > 1000) and (elevation < 1850))"

shuffle_data: true

channel_transformation: "log10"

data_balancing: "methode"

seed: 42

generate_results:
  quantitative:
    f1_score: true
    weighted_F1_score: true
    roc_curves: true
    conf_matrix: true
  qualitative:
    maps: true
    dates:
      - "15/05/2024"
      - "31/01/2023"
