data_path : "pipeline/data/dataset/dataset_AD_08200821_14Mas3Top3Phy_W15_corrected_V2.h5"

type : "local"

#Methode for the fold: kFold, mFold or combinationFold
methode_fold : "combinationFold"
seed : 42 

labeling_methode : "crocus"

BANDS_MAX:
   "a":
     - 0
     - 1

import : 
    - "from sklearn.svm import SVC"
    - "from sklearn.neighbors import KNeighborsClassifier"
    - "from sklearn.ensemble import AdaBoostClassifier,RandomForestClassifier"
    - "from sklearn.linear_model import LogisticRegression"
    - "from sklearn.neural_network import MLPClassifier"
    - "from estimators.statistical_descriptor import *"

name_pip: 
    - "KNN_direct"
    - "RandomForest_direct"
    - "MLP_direct"
    - "SVMrbf_direct"
    - "LogisticR_direct"
    - "AdaBoost_direct"    

pipeline:
# KNN 
    - - - "Hist_SAR"
      - - "KNeighborsClassifier"
        - n_neighbors: 50
        - n_jobs: -1
# #RandomForestClassifier
    - - - "Hist_SAR"
      - - "RandomForestClassifier"
        - n_estimators: 200
        - criterion : "entropy"
        - n_jobs: -1
# MLPClassifier
    - - - "Hist_SAR"
      - - "MLPClassifier"
        - alpha: 0.01
#SVC_RBF
    - - - "Hist_SAR"
      - - "SVC"
        - kernel: "rbf"
        - probability: 1
#LogisticRegression
    - - - "Hist_SAR"
      - - "LogisticRegression"
#AdaBoostClassifier
    - - - "Hist_SAR"
      - - "AdaBoostClassifier"
        - n_estimators: 200
