out_dir : "../results/comp_algos"
data_path : "pipeline/data/dataset/dataset_AD_08200821_14Mas3Top3Phy_W15_corrected.h5"
type : "local"

seed : 42 

BANDS_MAX:
   "a":
     - 0
     - 1

import : 
    - "from sklearn.svm import SVC"
    - "from sklearn.neighbors import KNeighborsClassifier"
    - "from sklearn.ensemble import AdaBoostClassifier,RandomForestClassifier"
    - "from sklearn.linear_model import LogisticRegression"
    - "from sklearn.neural_network import MLPClassifier"
    - "from statistical_descriptor import *"

name_pip: 
    - "KNN_direct"
    - "RandomForest_direct"
    - "MLP_direct"
    - "SVMrbf_direct"
    - "LogisticR_direct"
    - "AdaBoost_direct"    

pipeline:
# KNN 
    - - - "Hist_SAR"
      - - "KNeighborsClassifier"
        - n_neighbors: 50
        - n_jobs: -1
