# Path to the dataset file
data_path: "pipeline/data/dataset/dataset_AD_08200821_14Mas3Top3Phy_W15_corrected_V2.h5"

# Directory to save the output results
out_dir: "pipeline/results/"

# Method for the fold: kFold, mFold, or combinationFold
fold_method: "combinationFold"

# Random seed for reproducibility
seed: 100150

# Method for labeling: crocus
labeling_method: "crocus"

# Method for resampling: oversample, undersample, or smote
resampling_method: "undersample"

# Filter request based on date and elevation criteria
request: "(date.dt.month == 3 and date.dt.day == 1) and ((elevation > 1000) and (elevation < 1500))"

# Shuffle the data before processing
shuffle_data: true

# Balance the data
balance_data: false

# Transformation applied to the data channels (Not implemented)
channel_transformation: "log10"

# Maximum bands configuration (Not used for the moment)
BANDS_MAX:
   "a":
     - 0
     - 1

# Import necessary libraries and modules
import:
    - "from sklearn.svm import SVC"
    - "from sklearn.neighbors import KNeighborsClassifier"
    - "from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier"
    - "from sklearn.linear_model import LogisticRegression"
    - "from sklearn.neural_network import MLPClassifier"
    - "from estimators.statistical_descriptor import *"
    - "from estimators.band_selector import *"

# Names of the pipelines to be used
pipeline_names:
    - "KNN_direct"
    - "RandomForest_direct"
    - "MLP_direct"
    - "SVMrbf_direct"
    - "LogisticR_direct"
    - "AdaBoost_direct"

# Configuration for each pipeline
pipeline:
    # KNeighborsClassifier pipeline
    - - - "BandSelector"
        - bands: [0,1,2,3,4,5,6,7,8]
      - - "Hist_SAR"
      - - "KNeighborsClassifier"
        - n_neighbors: 50
        - n_jobs: -1
    # RandomForestClassifier pipeline
    - - - "BandSelector"
        - bands: [0,1,2,3,4,5,6,7,8]
      - - "Hist_SAR"
      - - "RandomForestClassifier"
        - n_estimators: 200
        - criterion: "entropy"
        - n_jobs: -1
    # MLPClassifier pipeline
    - - - "BandSelector"
        - bands: [0,1,2,3,4,5,6,7,8]
      - - "Hist_SAR"
      - - "MLPClassifier"
        - alpha: 0.01
    # SVC with RBF kernel pipeline
    - - - "BandSelector"
        - bands: [0,1,2,3,4,5,6,7,8]
      - - "Hist_SAR"
      - - "SVC"
        - kernel: "rbf"
        - probability: 1
    # LogisticRegression pipeline
    - - - "BandSelector"
        - bands: [0,1,2,3,4,5,6,7,8]
      - - "Hist_SAR"
      - - "LogisticRegression"
    # AdaBoostClassifier pipeline
    - - - "BandSelector"
        - bands: [0,1,2,3,4,5,6,7,8]
      - - "Hist_SAR"
      - - "AdaBoostClassifier"
        - n_estimators: 200

# Metrics to include in the final report
metrics_to_report:
    #- 'f1_score_macro'
    - 'f1_score_weighted'
    #- 'f1_score_multiclass'
    - 'accuracy_score'
    #- 'precision_score_macro'
    - 'recall_score_macro'
    #- 'roc_auc_score'
    #- 'log_loss'
    - 'kappa_score'
    - 'confusion_matrix'
